apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  namespace: system
type: Opaque
data:
  # Base64 encoded Slack webhook URL
  # Example: echo -n "https://hooks.slack.com/services/YOUR/WEBHOOK/URL" | base64
  webhook-url: ""
